steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/awesome-project/cloud-build-firebase:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/awesome-project/cloud-build-firebase:$SHORT_SHA']
